### ISSUE TITLE
Enhorabuena por tu primer repositorio!

### ISSUE THREAD

**Issue by dprada** [MirzaMinnie/Prueba#1]
Genial! Has creado tu primer repositorio. Como ves, por aquí otras personas pueden interaccionar contigo para reportar problemas, proponer cambios o solicitar ayuda.

Por favor, prueba a responderme por aquí para simular que mantenemos una conversación. 😄 :octocat:

**Comment by MirzaMinnie** [comment]
Muchas gracias por la orientación. Estoy aprendiendo muy bien. ¡Gracias por todo el tiempo aplicado en la enseñanza!

**Comment by dprada** [comment]
Muy bien! Entonces ahora ya puedes cerrar esta discusión.
Aquí abajo hay un botón que dice "Close with comment".
No te preocupes, la discusión no se pierde. Quedará almacenada bajo el estatus de "cerrada". Siempre se puede volver a consultar, o se puede reabrir.

Ahora la tarea es que, todavía a través de la web (sin un clon local de tu repo), recibas un Pull Request mio y lo aceptes.
Yo te aviso por whatsapp!

**Comment by MirzaMinnie** [comment]
Perfecto.
